In [2]:
print('Hello')

Hello


**numpy**

In [3]:
#numpy
list1 = [1,2,3,4]
print(list1)
list2 = [5,6]
print(list2)

[1, 2, 3, 4]
[5, 6]


In [4]:
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [6]:
list2 = [5,6,7,8]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [5]:
print(list1+2)

TypeError: can only concatenate list (not "int") to list

In [ ]:
%pip install numpy

You should consider upgrading via the 'F:\workspace\vsProjects\ML_AI_Batch\venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [8]:
import numpy as np
l1 = np.array(list1)
print(l1)

[1 2 3 4]


In [9]:
print(l1+2)

[3 4 5 6]


In [10]:
print((l1+3)/10)

[0.4 0.5 0.6 0.7]


In [11]:
l2 = np.array(list2)
print(l1+l2)

[ 6  8 10 12]


In [13]:
for l in l1:
    print(l)

1
2
3
4


**pandas**

In [ ]:
%pip install pandas

You should consider upgrading via the 'F:\workspace\vsProjects\ML_AI_Batch\venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [11]:
#Pandas
import pandas as pd

In [12]:
df = pd.Series([1,2,3,4,5,6])
df

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [16]:
df.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [17]:
df.tail()

1    2
2    3
3    4
4    5
5    6
dtype: int64

In [18]:
df.shape

(6,)

In [13]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 6 entries, 0 to 5
Series name: None
Non-Null Count  Dtype
--------------  -----
6 non-null      int64
dtypes: int64(1)
memory usage: 176.0 bytes


In [20]:
d1 = {'s1':10, 's2':20,'s3':30}
d2 = {'s1':50, 's2':60,'s3':70}


In [21]:
s1 = pd.Series(d1)
s2 = pd.Series(d2)

In [22]:
s1.head()

s1    10
s2    20
s3    30
dtype: int64

In [24]:
df = pd.DataFrame({'Student1':s1,'Student2':s2})
df

Student1  Student2
s1        10        50
s2        20        60
s3        30        70

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, s1 to s3
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Student1  3 non-null      int64
 1   Student2  3 non-null      int64
dtypes: int64(2)
memory usage: 72.0+ bytes


**Preprocessing**

!git clone https://github.com/Sarath-Coder-Hub/ml_dataset

In [2]:
import pandas as pd

In [41]:
df = pd.read_csv('./ml_dataset/purchase.csv')
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      NaN       Yes

In [4]:
df.shape

(10, 4)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [5]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [6]:
df.dropna()

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [7]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [20]:
df2 = df.dropna()
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    8 non-null      object 
 1   Age        8 non-null      float64
 2   Salary     8 non-null      float64
 3   Purchased  8 non-null      object 
dtypes: float64(2), object(2)
memory usage: 320.0+ bytes


In [21]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [38]:
#fillna
df.fillna(0)

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      0.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   0.0  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [39]:
d1 = {'Age':100,'Salary':200}
df.fillna(value=d1)

Country    Age   Salary Purchased
0   France   44.0  72000.0       No 
1    Spain   27.0  48000.0       Yes
2  Germany   30.0  54000.0       No 
3    Spain   38.0  61000.0       No 
4  Germany   40.0    200.0       Yes
5   France   35.0  58000.0       Yes
6    Spain  100.0  52000.0       No 
7   France   48.0  79000.0       Yes
8  Germany   50.0  83000.0       No 
9   France   37.0  67000.0       Yes

In [22]:
d1 = {'Age':df.Age.mean(),'Salary':df['Salary'].mean()}
df.fillna(value=d1)

Country        Age        Salary Purchased
0   France  44.000000  72000.000000       No 
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000       No 
3    Spain  38.000000  61000.000000       No 
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000       No 
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000       No 
9   France  37.000000  67000.000000       Yes

In [23]:
#df2 = df
#df2

In [24]:
#df2['Age'][7] = None

In [25]:
#df2

In [8]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [27]:
#d1 = {'Age':100,'Salary':200}
#df.fillna(value=d1)

In [28]:
#ffill, bfill
df.ffill()

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0  61000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  35.0  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [29]:
df.bfill()

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0  58000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  48.0  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

**Imputer**

In [32]:
%pip install scikit-learn

You should consider upgrading via the 'F:\workspace\vsProjects\ML_AI_Batch\venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [43]:

import numpy as np
from sklearn.impute import SimpleImputer

In [44]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [11]:
imputer.fit(df[['Age','Salary']])

SimpleImputer()

In [12]:
imputer.transform(df[['Age','Salary']])

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [45]:
df[['Age','Salary']] = imputer.fit_transform(df[['Age','Salary']])

In [46]:
df

Country        Age        Salary Purchased
0   France  44.000000  72000.000000       No 
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000       No 
3    Spain  38.000000  61000.000000       No 
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000       No 
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000       No 
9   France  37.000000  67000.000000       Yes

In [39]:
%pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'f:\workspace\vsProjects\ML_AI_Batch\venv\Scripts\python.exe -m pip install --upgrade pip' command.


**Encoding**
**Label Encoder**
- Converts text to numeric value

In [14]:
from sklearn.preprocessing import LabelEncoder

In [32]:
le_purchased = LabelEncoder()
df['Purchased'] = le_purchased.fit_transform(df['Purchased'])
print(df)

   Country        Age        Salary  Purchased
0   France  44.000000  72000.000000          0
1    Spain  27.000000  48000.000000          1
2  Germany  30.000000  54000.000000          0
3    Spain  38.000000  61000.000000          0
4  Germany  40.000000  63777.777778          1
5   France  35.000000  58000.000000          1
6    Spain  38.777778  52000.000000          0
7   France  48.000000  79000.000000          1
8  Germany  50.000000  83000.000000          0
9   France  37.000000  67000.000000          1


In [33]:
le_purchased.classes_

array(['No ', 'Yes'], dtype=object)

In [18]:
for i in df['Purchased']:
    print(i, le_purchased.classes_[i])


0 No 
1 Yes
0 No 
0 No 
1 Yes
1 Yes
0 No 
1 Yes
0 No 
1 Yes


In [34]:
le_country = LabelEncoder()
df['Country'] = le_country.fit_transform(df['Country'])
print(df)

   Country        Age        Salary  Purchased
0        0  44.000000  72000.000000          0
1        2  27.000000  48000.000000          1
2        1  30.000000  54000.000000          0
3        2  38.000000  61000.000000          0
4        1  40.000000  63777.777778          1
5        0  35.000000  58000.000000          1
6        2  38.777778  52000.000000          0
7        0  48.000000  79000.000000          1
8        1  50.000000  83000.000000          0
9        0  37.000000  67000.000000          1


In [35]:
le_country.classes_

array(['France', 'Germany', 'Spain'], dtype=object)

In [37]:
le_purchased.transform(['Yes','No ','Yes'])

array([1, 0, 1])

In [38]:
le_purchased.inverse_transform([0,0,1])

array(['No ', 'No ', 'Yes'], dtype=object)

Save the dataframe

In [39]:
import pickle

In [40]:
with open('./out/preprocessed_df.pickle', 'wb') as file:
    pickle.dump(df, file)

**One Hot Encoding**

In [47]:
df.head()

Country   Age        Salary Purchased
0   France  44.0  72000.000000       No 
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000       No 
3    Spain  38.0  61000.000000       No 
4  Germany  40.0  63777.777778       Yes

In [48]:
import pandas as pd

In [49]:
df = pd.get_dummies(df, columns=['Country'])
df.head()

Age        Salary Purchased  Country_France  Country_Germany  \
0  44.0  72000.000000       No             True            False   
1  27.0  48000.000000       Yes           False            False   
2  30.0  54000.000000       No            False             True   
3  38.0  61000.000000       No            False            False   
4  40.0  63777.777778       Yes           False             True   

   Country_Spain  
0          False  
1           True  
2          False  
3           True  
4          False

**Scaling**

In [50]:
from sklearn.preprocessing import StandardScaler

In [51]:
scaler = StandardScaler()

In [52]:
df[['Age', 'Salary']] = scaler.fit_transform(df[['Age','Salary']])

In [53]:
df.head()

Age        Salary Purchased  Country_France  Country_Germany  \
0  0.758874  7.494733e-01       No             True            False   
1 -1.711504 -1.438178e+00       Yes           False            False   
2 -1.275555 -8.912655e-01       No            False             True   
3 -0.113024 -2.532004e-01       No            False            False   
4  0.177609  6.632192e-16       Yes           False             True   

   Country_Spain  
0          False  
1           True  
2          False  
3           True  
4          False

In [54]:
#write as csv
df.to_csv('./out/preprocessed.csv', index=False, encoding='utf-8', header=True)

In [55]:
df.head()


Age        Salary Purchased  Country_France  Country_Germany  \
0  0.758874  7.494733e-01       No             True            False   
1 -1.711504 -1.438178e+00       Yes           False            False   
2 -1.275555 -8.912655e-01       No            False             True   
3 -0.113024 -2.532004e-01       No            False            False   
4  0.177609  6.632192e-16       Yes           False             True   

   Country_Spain  
0          False  
1           True  
2          False  
3           True  
4          False

In [56]:
df2 = pd.read_csv('./out/preprocessed.csv')
df2.head()

Age        Salary Purchased  Country_France  Country_Germany  \
0  0.758874  7.494733e-01       No             True            False   
1 -1.711504 -1.438178e+00       Yes           False            False   
2 -1.275555 -8.912655e-01       No            False             True   
3 -0.113024 -2.532004e-01       No            False            False   
4  0.177609  6.632192e-16       Yes           False             True   

   Country_Spain  
0          False  
1           True  
2          False  
3           True  
4          False

**Test Train Split**

In [57]:
X = df2.drop('Purchased', axis=1)
X

Age        Salary  Country_France  Country_Germany  Country_Spain
0  0.758874  7.494733e-01            True            False          False
1 -1.711504 -1.438178e+00           False            False           True
2 -1.275555 -8.912655e-01           False             True          False
3 -0.113024 -2.532004e-01           False            False           True
4  0.177609  6.632192e-16           False             True          False
5 -0.548973 -5.266569e-01            True            False          False
6  0.000000 -1.073570e+00           False            False           True
7  1.340140  1.387538e+00            True            False          False
8  1.630773  1.752147e+00           False             True          False
9 -0.258340  2.937125e-01            True            False          False

In [58]:
y = df2['Purchased']
y

0    No 
1    Yes
2    No 
3    No 
4    Yes
5    Yes
6    No 
7    Yes
8    No 
9    Yes
Name: Purchased, dtype: object

In [59]:
#splitting
from sklearn.model_selection import train_test_split

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,
                                                    random_state=12)
print(X_train.head())
print(y_train.head())


        Age        Salary  Country_France  Country_Germany  Country_Spain
7  1.340140  1.387538e+00            True            False          False
0  0.758874  7.494733e-01            True            False          False
4  0.177609  6.632192e-16           False             True          False
9 -0.258340  2.937125e-01            True            False          False
3 -0.113024 -2.532004e-01           False            False           True
7    Yes
0    No 
4    Yes
9    Yes
3    No 
Name: Purchased, dtype: object
